### ISSUE TITLE
Probability of existance in the prediction step

### ISSUE THREAD

**Issue by LongfeiDE** [yuhsuansia/Trajectory-PMB-EOT-BP#3]
Hello, 

I'm curious about this line here:
https://github.com/yuhsuansia/Trajectory-PMB-EOT-BP/blob/0867c9b00d7aa9d0ca5d1ae6f7bd4292191cece8/TrajectoryPMB-EOT-BP/eotEllipticalShapeRFS.m#L65
Why should the probability of existance in the prediction be calculated like this?

I could find two equations in your paper "Poisson Multi-Bernoulli Approximations for Multiple Extended Object Filtering": 13d and 14d. It seems like 13d is used. 

Thanks.

**Comment by yuhsuansia** [comment]
Hi,

Thanks for your question.

This line does not correspond to the prediction step. It is instead related to the initialization step of the loopy belief propagation described in the paper "[Trajectory PMB filters for extended object tracking using belief propagation]". You may still need to do some simple calculations based on the equation in the paper to obtain the equation in the code though. 

If you are looking for the code of the prediction step of the trajectory PMB(M) filter, it would be better to have a look at my other TPMB(M) repo.

Best,
Yuxuan

**Comment by LongfeiDE** [comment]
Thanks for the quick reply!
